### ISSUE TITLE
Does not work with Android Studio 3.0 Canary 1

### ISSUE THREAD

**Issue by carmas123** [general-mobile/kotlin-android-mvp-starter#2]
If I try to compile with Android Studio 3.0 Canary 1 I got this exception:

Error:Execution failed for task ':app:fabricGenerateResourcesDebug'.
> Crashlytics Developer Tools error.

Thanks

**Comment by msayan** [comment]
You should set your crashlytics api key to AndroidManifefs.xml
There is an TODO for that 
`<meta-data
            android:name="io.fabric.ApiKey"
            android:value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" />`

**Comment by carmas123** [comment]
Solved...it's true, sorry me
It work
