### ISSUE TITLE
Dagger problem

### ISSUE THREAD

**Issue by carmas123** [general-mobile/kotlin-android-mvp-starter#4]
```
import com.myapp.di.component.DaggerApplicationComponent
class Application : android.app.Application() {

    override fun onCreate() {
        super.onCreate()

        //di
        component = DaggerApplicationComponent.builder().applicationModule(ApplicationModule(this)).build() 
```

DaggerApplicationComponent is not found

**Comment by msayan** [comment]
just rebuild the project

**Comment by carmas123** [comment]
mmm... but the file DaggerApplicationComponent does not exist

**Comment by carmas123** [comment]
I try to rebuild but nothing

**Comment by msayan** [comment]
dagger files created when project builds. Just build project and try to import it again.

**Comment by carmas123** [comment]
Always this error
DaggerApplicationComponent

**Comment by msayan** [comment]
you should look at [dagger 2](https://github.com/google/dagger)

**Comment by carmas123** [comment]
Try to create app with cookiecutter with all component Y skipping Realm and you see the problem

**Comment by dtunctuncer** [comment]
I have checked there is no problem i am closing issue now
